services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    image: playwright
    container_name: playwright
    ports:
      - "9323:9323"
    volumes:
      - ./:/workspace:delegated
    command: tail -f /dev/null